lab5/RailroadTransport/RailroadTransport/Models/Stop.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RailroadTransport.Models
{
    public class Stop
    {
        [Key]
        [Display(Name = "Код остановки")]
        public int StopId { get; set; }
        [Display(Name = "Название остановки")]
        public string NameOfStop { get; set; }
        [Display(Name = "Является ли станцией")]
        public bool IsStation { get; set; }
        [Display(Name = "Имеется ли зал ожидания")]
        public bool IsHall { get; set; }
        public ICollection<Schedule> ScheduleStop { get; set; }
    }
}

lab5/RailroadTransport/RailroadTransport/ViewModels/Tables/StopViewModel.cs
using RailroadTransport.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RailroadTransport.ViewModels
{
    public class StopViewModel
    {
        public string NameOfStop { get; set; }
        public IEnumerable<Stop> Stops { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public SortViewModel SortViewModel { get; set; }
    }
}

lab5/RailroadTransport/RailroadTransport/Controllers/Tables/StopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using RailroadTransport.Data;
using RailroadTransport.Models;
using RailroadTransport.ViewModels;

namespace RailroadTransport.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StopController : Controller
    {
        private RailroadContext railroadContext;
        private IMemoryCache cache;
        public StopController(RailroadContext rc, IMemoryCache cache)
        {
            railroadContext = rc;
            this.cache = cache;
        }
        public IActionResult Index(string NameOfStop, SortState sortState, int page = 1)
        {
            StopViewModel viewModel;
            if (!cache.TryGetValue("stopViewModel", out viewModel))
            {
                viewModel = SetViewModel(NameOfStop, sortState, page);
                cache.Set("stopViewModel", viewModel);
            }
            else
            {
                viewModel = SetViewModel(NameOfStop ?? viewModel.NameOfStop, sortState, page);
                cache.Set("stopViewModel", viewModel);
            }
            return View(viewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create([Bind("StopId,NameOfStop")] Stop stop)
        {
            if (!String.IsNullOrEmpty(stop.NameOfStop))
            {
                railroadContext.Stops.Add(stop);
                railroadContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stop);
        }

        public IActionResult Edit(int? id)
        {
            var stop = railroadContext.Stops.Find(id);
            return View(stop);
        }
        [HttpPost]
        public IActionResult Edit([Bind("StopId,NameOfStop")] Stop stop)
        {
            railroadContext.Update(stop);
            railroadContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int? id)
        {
            var post = railroadContext.Stops.Find(id);
            return View(post);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleConfirmed(int id)
        {
            var stop = railroadContext.Stops.Find(id);
            var Stop = railroadContext.Schedules.Where(b => b.StopId == id);
            railroadContext.Schedules.RemoveRange(Stop);
            railroadContext.Stops.Remove(stop);
            railroadContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public IEnumerable<Stop> SortSearch(IEnumerable<Stop> stops, SortState sortState, string NameOfStop)
        {
            stops = stops.Where(n => n.NameOfStop.Contains(NameOfStop ?? ""));
            switch (sortState)
            {
                case SortState.NameOfStopAcs:
                    stops = stops.OrderBy(n => n.NameOfStop);
                    break;
                case SortState.NameOfStopDecs:
                    stops = stops.OrderByDescending(n => n.NameOfStop);
                    break;
            }
            return stops;
        }
        public IActionResult ClearCache()
        {
            cache.Remove("stopViewModel");
            return RedirectToAction("Index");
        }
        private StopViewModel SetViewModel(string NameOfStop, SortState sortState, int page = 1)
        {
            IEnumerable<Stop> stops = railroadContext.Stops;
            stops = SortSearch(stops, sortState, NameOfStop ?? "");
            int pageSize = 10;
            int count = stops.Count();
            stops = stops.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            StopViewModel viewModel = new StopViewModel
            {
                Stops = stops,
                PageViewModel = pageViewModel,
                NameOfStop = NameOfStop,
                SortViewModel = new SortViewModel(sortState)
            };
            return viewModel;
        }
    }
}

lab5/RailroadTransport/RailroadTransport/Views/Stop/Create.cshtml
@model RailroadTransport.Models.Stop

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавление</h2>

<form asp-action="Create">
    <input type="hidden" asp-for="StopId" />
    <div class="form-group">
        <label asp-for="NameOfStop" class="control-label"></label>
        <input asp-for="NameOfStop" class="form-control" name="NameOfStop" />
    </div>
    <div class="form-group">
        <label asp-for="IsStation" class="control-label"></label>
        <select asp-for="IsStation" class="form-control">
            <option disabled>Является ли станцией</option>
            <option value="True">True</option>
            <option value="False">False</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="IsHall" class="control-label"></label>
        <select asp-for="IsHall" class="form-control">
            <option disabled>Имеется ли зал ожидания</option>
            <option value="True">True</option>
            <option value="False">False</option>
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-outline-dark" />
    </div>
</form>

lab5/RailroadTransport/RailroadTransport/Views/Stop/Delete.cshtml
@model RailroadTransport.Models.Stop

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удаление</h2>

<dl>
    <dt>@Html.DisplayNameFor(model => model.StopId)</dt>
    <dd>@Html.DisplayFor(model => model.StopId)</dd>
    <dt>@Html.DisplayNameFor(model => model.NameOfStop)</dt>
    <dd>@Html.DisplayFor(model => model.NameOfStop)</dd>
    <dt>@Html.DisplayNameFor(model => model.IsStation)</dt>
    <dd>@Html.DisplayFor(model => model.IsStation)</dd>
    <dt>@Html.DisplayNameFor(model => model.IsHall)</dt>
    <dd>@Html.DisplayFor(model => model.IsHall)</dd>
</dl>
<form asp-action="Delete">
    <input type="hidden" asp-for="StopId" />
    <input type="submit" value="Удалить" class="btn btn-outline-dark" /> |
    <a class="btn btn-outline-dark" asp-action="Index">Вернуться к списку</a>
</form>

lab5/RailroadTransport/RailroadTransport/Views/Stop/Edit.cshtml
@model RailroadTransport.Models.Stop

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактировать</h2>
<form action="edit" method="post">
    <input type="hidden" asp-for="StopId" />
    <div class="form-group">
        <label asp-for="NameOfStop" class="control-label"></label>
        <input asp-for="NameOfStop" class="form-control" name="NameOfStop" />
    </div>
    <div class="form-group">
        <label asp-for="IsStation" class="control-label"></label>
        <select asp-for="IsStation" class="form-control">
            <option disabled>Является ли станцией</option>
            <option value="True">True</option>
            <option value="False">False</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="IsHall" class="control-label"></label>
        <select asp-for="IsHall" class="form-control">
            <option disabled>Имеется ли зал ожидания</option>
            <option value="True">True</option>
            <option value="False">False</option>
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-dark" />
    </div>
</form>

lab5/RailroadTransport/RailroadTransport/Views/Stop/Index.cshtml
@model RailroadTransport.ViewModels.StopViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string nameOfStop = Model.NameOfStop;
}

<h2>Остановки</h2>

<p><a class="btn btn-outline-dark" asp-action="Create">Добавить</a></p>
<p><a class="btn btn-outline-dark" asp-action="ClearCache">Очистить фильтр</a></p>
@using (Html.BeginForm("Index", "Stop", FormMethod.Get))
{
    <fieldset>
        Наименование остановки: @Html.TextBox("NameOfStop", Model.NameOfStop)
        <input class="btn btn-outline-dark" type="submit" value="Найти" />
    </fieldset>
}

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Stops.FirstOrDefault().StopId)</th>
            <th><a asp-action="Index" asp-route-sortState=@Model.SortViewModel.NameOfStopSort asp-route-NameOfStop="@nameOfStop">
                @Html.DisplayNameFor(model => model.Stops.FirstOrDefault().NameOfStop)</a>
            </th>
            <th>@Html.DisplayNameFor(model => model.Stops.FirstOrDefault().IsStation)</th>
            <th>@Html.DisplayNameFor(model => model.Stops.FirstOrDefault().IsHall)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Stops)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.StopId)</td>
                <td>@Html.DisplayFor(modelItem => item.NameOfStop)</td>
                <td>@Html.DisplayFor(modelItem => item.IsStation)</td>
                <td>@Html.DisplayFor(modelItem => item.IsHall)</td>
                <td>
                    <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.StopId">Редактировать</a> |
                    <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@item.StopId">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}